import Vue from 'vue'
import { Button, Field, Cell, CellGroup, Toast, Popup, Icon, Tab, Tabs, Image as VanImage, Row, Col, Swipe, SwipeItem, GridItem, Grid, Card, List, Overlay, Collapse, CollapseItem, Search, Pagination, Slider } from 'vant'

Vue.use(Button)
Vue.use(Field)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(Toast)
Vue.use(Popup)
Vue.use(Icon)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(VanImage)
Vue.use(Col)
Vue.use(Row)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Card)
Vue.use(List)
Vue.use(Overlay)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(Search)
Vue.use(Pagination)
Vue.use(Slider)
